# Generated by Django 4.0.6 on 2022-11-19 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_priority', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ship_from_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_receive_transfers', to='accounts.facility')),
                ('ship_to_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_sent_transfers', to='accounts.facility')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_level', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_of_measure', models.CharField(choices=[('pack', 'pack(s)'), ('batch', 'batch'), ('volume', 'volume'), ('weight', 'weight'), ('unit', 'unit')], max_length=20)),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Not Released', 'Not Released'), ('Partial', 'Partial'), ('Released', 'Released'), ('Delivered', 'Delivered')], max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulary_stock_transfer', to='formulary.productlist')),
                ('stock_transfer_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_products', to='outbound.stocktransfer')),
            ],
        ),
    ]
