# Generated by Django 4.0.6 on 2022-11-21 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0002_remove_productlist_unit_of_measure_unitofmeasure'),
        ('billing', '0002_pricelist_created_date_pricelist_updated_date'),
        ('outbound', '0002_salesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 21, 14, 55, 51, 747030, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Cancelled', 'Cancelled'), ('Partial', 'Partial'), ('Finished', 'Finished'), ('Delivered', 'Delivered')], default='Not Started', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransferproducts',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stocktransferproducts',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Cancelled', 'Cancelled'), ('Not Released', 'Not Released'), ('Partial', 'Partial'), ('Released', 'Released'), ('Delivered', 'Delivered')], default='Not Started', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransferproducts',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SalesOrdersProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_level', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_of_measure', models.CharField(choices=[('pack', 'pack'), ('batch', 'batch'), ('volume', 'volume'), ('kg', 'kg'), ('unit', 'unit')], default='pack', max_length=20)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Cancelled', 'Cancelled'), ('Not Released', 'Not Released'), ('Partial', 'Partial'), ('Released', 'Released'), ('Delivered', 'Delivered')], default='Not Started', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.pricelist')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulary_sales_order', to='formulary.productlist')),
                ('stock_transfer_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_products', to='outbound.stocktransfer')),
            ],
        ),
    ]
