# Generated by Django 4.0.6 on 2022-11-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0003_salesorder_created_date_salesorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesordersproducts',
            name='unit_of_measure',
            field=models.CharField(choices=[('Packs', 'Packs'), ('Units', 'Units'), ('Volume in Mls', 'Volume in Mls'), ('Weight in Grams', 'Weight in Grams')], default='pack', max_length=20),
        ),
    ]
