# Generated by Django 4.0.6 on 2022-11-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0004_alter_salesordersproducts_unit_of_measure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransferproducts',
            old_name='products',
            new_name='product',
        ),
    ]
