# Generated by Django 4.0.6 on 2022-11-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0005_rename_products_stocktransferproducts_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Partial', 'Partial'), ('Finished', 'Finished'), ('Delivered', 'Delivered'), ('Not Started', 'Not Started')], default='Not Started', max_length=20),
        ),
    ]
