# Generated by Django 4.0.6 on 2022-11-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0009_alter_unitofmeasure_pack'),
        ('outbound', '0006_stocktransfer_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockTransferProducts',
            new_name='StockTransferProduct',
        ),
    ]
