# Generated by Django 4.0.6 on 2022-11-23 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('outbound', '0008_salesorderproduct_delete_salesordersproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderproduct',
            name='ship_from_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_sales_transfers', to='accounts.facility'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='ship_from_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_receipts', to='accounts.facility'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='ship_to_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_transfers', to='accounts.facility'),
        ),
    ]
