# Generated by Django 4.0.6 on 2022-11-23 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outbound', '0009_salesorderproduct_ship_from_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='external_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
