# Generated by Django 4.0.6 on 2022-11-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0010_salesorder_external_reference_salesorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransferproduct',
            name='unit_of_measure',
            field=models.CharField(choices=[('Packs', 'Packs'), ('Units', 'Units'), ('Volume in Mls', 'Volume in Mls'), ('Weight in Grams', 'Weight in Grams')], max_length=20),
        ),
    ]
