# Generated by Django 4.0.6 on 2022-11-24 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0011_alter_stocktransferproduct_unit_of_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransferproduct',
            name='inventory_level',
        ),
    ]
