# Generated by Django 4.0.6 on 2022-11-24 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_stock_identifier'),
        ('accounts', '0001_initial'),
        ('formulary', '0009_alter_unitofmeasure_pack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outbound', '0012_remove_stocktransferproduct_inventory_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Finished', 'Finished'), ('Not Started', 'Not Started')], default='Not Started', max_length=20)),
                ('order_priority', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ship_from_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_picks', to='accounts.facility')),
                ('ship_to_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_packs', to='accounts.facility')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_pickpack', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='stocktransferproduct',
            name='unit_of_measure',
            field=models.CharField(choices=[('Packs', 'Packs'), ('Units', 'Units'), ('Volume in Mls', 'Volume in Mls'), ('Weight in Grams', 'Weight in Grams')], default='Packs', max_length=20),
        ),
        migrations.CreateModel(
            name='PickPackProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('batch_number', models.CharField(blank=True, max_length=225, null=True)),
                ('expiration_date', models.DateField()),
                ('stock_identifier', models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Unique Identifier')),
                ('unit_of_measure', models.CharField(choices=[('Packs', 'Packs'), ('Units', 'Units'), ('Volume in Mls', 'Volume in Mls'), ('Weight in Grams', 'Weight in Grams')], default='Packs', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('logistic_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.logisticarea')),
                ('pickpack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickpack_products', to='outbound.pickpack')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulary_pickpack', to='formulary.productlist')),
            ],
        ),
    ]
