# Generated by Django 4.0.6 on 2022-11-24 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0009_alter_unitofmeasure_pack'),
        ('inventory', '0003_alter_inventory_stock_identifier'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outbound', '0013_pickpack_alter_stocktransferproduct_unit_of_measure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Finished', 'Finished'), ('Not Started', 'Not Started')], default='Not Started', max_length=20)),
                ('order_priority', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ship_from_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_ship_from', to='accounts.facility')),
                ('ship_to_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_ship_to', to='accounts.facility')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_delivery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('batch_number', models.CharField(blank=True, max_length=225, null=True)),
                ('expiration_date', models.DateField()),
                ('stock_identifier', models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Unique Identifier')),
                ('unit_of_measure', models.CharField(choices=[('Packs', 'Packs'), ('Units', 'Units'), ('Volume in Mls', 'Volume in Mls'), ('Weight in Grams', 'Weight in Grams')], default='Packs', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_products', to='outbound.delivery')),
                ('logistic_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.logisticarea')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulary_delivery', to='formulary.productlist')),
            ],
        ),
    ]
