# Generated by Django 4.0.6 on 2022-12-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0014_delivery_deliveryproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'Deliveries'},
        ),
    ]
