# Generated by Django 4.0.6 on 2022-12-03 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0015_alter_delivery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickpack',
            name='stock_transfer_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_picks', to='outbound.stocktransfer'),
        ),
    ]
