# Generated by Django 4.0.6 on 2022-12-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0016_pickpack_stock_transfer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickpack',
            name='sales_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_picks', to='outbound.stocktransfer'),
        ),
    ]
