# Generated by Django 4.0.6 on 2022-12-04 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outbound', '0017_pickpack_sales_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickpack',
            name='user',
        ),
        migrations.AddField(
            model_name='pickpack',
            name='user_ordered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ordered_pickpack', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickpack',
            name='user_processed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_processed_pickpack', to=settings.AUTH_USER_MODEL),
        ),
    ]
