# Generated by Django 4.0.6 on 2022-12-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0019_alter_pickpack_sales_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickpackproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Unique Identifier'),
        ),
    ]
