# Generated by Django 4.0.6 on 2022-12-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0020_alter_pickpackproduct_stock_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransferproduct',
            name='inventory_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
