# Generated by Django 4.0.6 on 2022-12-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0021_stocktransferproduct_inventory_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='stock_transfer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
