version: '3.9'

services:
    web:
        build: .
        container_name: lims_container
        command: >
            bash -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
        ports: 
            - 10555:8000
        volumes:
            - .:/lims
        stdin_open: true
        tty: true
        depends_on:
            - db

    

    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_DB=lims_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - pgdata:/var/lib/postgres/data
        ports: 
            - 5555:5432

volumes:
    pgdata:
    