# Generated by Django 4.0.6 on 2022-08-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_facility_site_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplied_products',
        ),
    ]
