# Generated by Django 4.0.6 on 2022-08-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100, null=True, unique=True)),
                ('facility_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
