# Generated by Django 4.0.6 on 2022-08-17 05:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0002_alter_category_options'),
        ('accounts', '0005_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100, null=True, unique=True)),
                ('supplier_location', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=225, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email_address', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('description', models.TextField(blank=True, max_length=225, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplied_products', models.ManyToManyField(to='formulary.product_list')),
            ],
            options={
                'verbose_name': 'Supplier',
                'ordering': ['-created_date'],
            },
        ),
    ]
