# Generated by Django 4.0.6 on 2022-09-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_supplier_location_supplier_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='description',
        ),
    ]
