# Generated by Django 4.0.6 on 2022-09-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_supplier_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='postbox',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
