# Generated by Django 4.0.6 on 2022-09-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_supplier_postbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
