# Generated by Django 4.0.6 on 2022-08-24 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulary', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.SlugField(max_length=100, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('facilty_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.facility')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100, unique=True)),
                ('area_description', models.CharField(max_length=100)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.site')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.CharField(choices=[('Warehouse', 'Warehouse'), ('In-Transit', 'In-Transit'), ('Delivered', 'Delivered')], max_length=100)),
                ('pack_quantity', models.IntegerField(verbose_name='Number of packs')),
                ('expiration_date', models.DateTimeField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.product_list')),
                ('site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.site')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
            },
        ),
    ]
