# Generated by Django 4.0.6 on 2022-08-14 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.CharField(choices=[('Warehouse', 'Warehouse'), ('In-Transit', 'In-Transit'), ('Delivered', 'Delivered')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_quantity', models.IntegerField(verbose_name='Number of packs')),
                ('inventory_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory_data')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.product_list')),
            ],
        ),
    ]
