# Generated by Django 4.0.6 on 2022-11-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Unique Identifier'),
        ),
    ]
