# Generated by Django 4.0.6 on 2022-08-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_facilty_name_site_facilty_remove_site_site_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='facilty',
            new_name='facility',
        ),
    ]
