# Generated by Django 4.0.6 on 2022-08-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_facilty_site_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_type',
            field=models.CharField(choices=[('Warehouse', 'Warehouse'), ('Pre-Delivered', 'Pre-Delivered'), ('In-Transit', 'In-Transit')], max_length=100),
        ),
    ]
