# Generated by Django 4.0.6 on 2022-12-03 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0009_alter_unitofmeasure_pack'),
        ('inventory', '0003_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_products', to='formulary.productlist'),
        ),
    ]
