# Generated by Django 4.0.6 on 2022-12-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='batch',
            new_name='batch_number',
        ),
    ]
