# Generated by Django 4.0.6 on 2022-08-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_stock_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='date_added',
            new_name='created_date',
        ),
    ]
