# Generated by Django 4.0.6 on 2022-08-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_date_added_site_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='site_id',
        ),
        migrations.AddField(
            model_name='inventory',
            name='batch',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='logistic_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.logisticarea'),
        ),
    ]
