# Generated by Django 4.0.6 on 2022-12-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_batch_inventory_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_type',
            field=models.CharField(choices=[('Warehouse', 'Warehouse'), ('Pre-Delivered', 'Pre-Delivered'), ('Delivered', 'Delivered')], max_length=100),
        ),
    ]
