# Generated by Django 4.0.6 on 2022-08-27 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventory_site_id_inventory_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('dd477a3a-e9bb-4609-a8d9-fa3d2aa189e9')),
        ),
    ]
