# Generated by Django 4.0.6 on 2022-08-27 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('5b7d3c82-becd-4b09-9693-28a4285a8a6f')),
        ),
    ]
