# Generated by Django 4.0.6 on 2022-12-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
