# Generated by Django 4.0.6 on 2022-12-04 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_inventory', to='inventory.site'),
        ),
    ]
