# Generated by Django 4.0.6 on 2022-12-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventory_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_inventory', to='inventory.site'),
        ),
    ]
