# Generated by Django 4.0.6 on 2022-08-27 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('7d26ea0f-4ae1-48ad-8575-6c6ab4948105')),
        ),
    ]
