# Generated by Django 4.0.6 on 2022-08-27 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('e6b18f4e-bad8-4957-b6f3-43103b4d356a')),
        ),
    ]
