# Generated by Django 4.0.6 on 2022-08-27 23:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('7698e8d5-33fe-4238-8e50-9d6fa2600857')),
        ),
    ]
