# Generated by Django 4.0.6 on 2022-08-27 23:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('d9605abb-d6db-4a3a-9ec1-053f4e567768')),
        ),
    ]
