# Generated by Django 4.0.6 on 2022-08-28 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('f2844fe9-3633-491f-8432-9b4de04726a3')),
        ),
    ]
