# Generated by Django 4.0.6 on 2022-08-28 00:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('0e7d94e7-19a2-4a94-80a7-6e757a325873')),
        ),
    ]
