# Generated by Django 4.0.6 on 2022-08-28 00:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('0821483e-aedb-4965-ba0a-1d39b48faa59')),
        ),
    ]
