# Generated by Django 4.0.6 on 2022-09-01 23:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('fbb237f4-3b91-4ae3-a679-a758c1a40423')),
        ),
    ]
