# Generated by Django 4.0.6 on 2022-09-01 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('b7c154b4-a695-4e6d-a27d-7d5ba11faf47')),
        ),
    ]
