# Generated by Django 4.0.6 on 2022-09-01 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('c0a5c59c-5c22-4d9d-9110-d85439ebb5f8')),
        ),
    ]
