# Generated by Django 4.0.6 on 2022-09-02 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('aaf52b21-2edf-4099-b6bd-b18f26ac3c19')),
        ),
    ]
