# Generated by Django 4.0.6 on 2022-09-03 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('a334dd1f-fc8c-49cf-9ce2-0b29deb63e14')),
        ),
    ]
