# Generated by Django 4.0.6 on 2022-09-03 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('1e75352b-085c-467a-b6a2-6fa4afa6a33b')),
        ),
    ]
