# Generated by Django 4.0.6 on 2022-09-03 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('b5f6f150-c9dc-402a-b4be-f0860f558e68')),
        ),
    ]
