# Generated by Django 4.0.6 on 2022-09-03 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('c78ce782-ed5f-4c0a-9d50-d8d70eab7f1e')),
        ),
    ]
