# Generated by Django 4.0.6 on 2022-09-03 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('0aba7ad4-ebb4-4ae0-aa5e-e9540ce7a6b6')),
        ),
    ]
