# Generated by Django 4.0.6 on 2022-09-03 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('5560325c-bba4-46e9-a7a7-1e9db0de8e38')),
        ),
    ]
