# Generated by Django 4.0.6 on 2022-09-03 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('c625f91d-a3ce-4372-b0de-a4241c9064ff')),
        ),
    ]
