# Generated by Django 4.0.6 on 2022-09-03 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('aae7f184-9956-4e30-b7e8-b5820e148acb')),
        ),
    ]
