# Generated by Django 4.0.6 on 2022-09-04 20:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('19a27a62-b369-43b9-abbc-ac6582fc56ba')),
        ),
    ]
