# Generated by Django 4.0.6 on 2022-09-04 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('e10faa58-5002-4dad-b60d-7e9a39e5d83d')),
        ),
    ]
