# Generated by Django 4.0.6 on 2022-09-04 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('9ce80ebf-45ba-48e6-b2b1-6f30bb738b21')),
        ),
    ]
