# Generated by Django 4.0.6 on 2022-09-05 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('ae1ce345-fb81-4eaf-9c4b-7334789d81fe')),
        ),
    ]
