# Generated by Django 4.0.6 on 2022-09-18 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('10caafb2-50b2-4219-b77e-31a2c47533c9')),
        ),
    ]
