# Generated by Django 4.0.6 on 2022-09-18 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('b7c9d89a-99bf-4acd-bf02-3eea8b40272d')),
        ),
    ]
