# Generated by Django 4.0.6 on 2022-09-18 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('e1c6a0fe-8fe3-4dbb-9752-e794eb65df93')),
        ),
    ]
