# Generated by Django 4.0.6 on 2022-09-18 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('aa1b3bba-bbd0-4207-91c6-e8a0428f2f05')),
        ),
    ]
