# Generated by Django 4.0.6 on 2022-09-18 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('f4327ec4-2ea2-475b-8ae5-dd83601c7f54')),
        ),
    ]
