# Generated by Django 4.0.6 on 2022-09-18 21:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('a1e8198e-5b5b-4f64-88ca-d5731c8bfec5')),
        ),
    ]
