# Generated by Django 4.0.6 on 2022-09-18 21:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('6a9729c4-3cf3-4dba-b544-96aaec81200d')),
        ),
        migrations.AlterField(
            model_name='logisticarea',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='inventory.site'),
        ),
    ]
