# Generated by Django 4.0.6 on 2022-09-19 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('fab44730-ae7a-4ea8-87e7-d5bdea797e3f')),
        ),
    ]
