# Generated by Django 4.0.6 on 2022-09-19 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('0d5b80ba-7ced-479c-9a09-084dc5b35ac1')),
        ),
    ]
