# Generated by Django 4.0.6 on 2022-09-19 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('921b99dc-d932-4314-8d36-e853fc7ebd5e')),
        ),
    ]
