# Generated by Django 4.0.6 on 2022-09-19 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0063_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('c6be6d82-83a2-49b9-904d-740299bf3b29')),
        ),
    ]
