# Generated by Django 4.0.6 on 2022-09-19 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('7912836b-7fba-45dd-8f3b-45031637e1d7')),
        ),
    ]
