# Generated by Django 4.0.6 on 2022-09-20 03:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('f2ace5b1-5f94-4c11-ab14-a2bda9d36de9')),
        ),
    ]
