# Generated by Django 4.0.6 on 2022-09-20 03:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('0c1dbb0e-cc75-495b-a3ca-d7fe7a1b82d9')),
        ),
    ]
