# Generated by Django 4.0.6 on 2022-09-20 03:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0070_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('50e2d335-b033-43dc-ae72-c90a0a7c7e02')),
        ),
    ]
