# Generated by Django 4.0.6 on 2022-09-23 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0072_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('8f819b59-56c4-44e5-9725-9ccda02e162f')),
        ),
    ]
