# Generated by Django 4.0.6 on 2022-09-25 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0073_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('e45870d3-441e-4727-ba6b-a5c2c6d20b75')),
        ),
    ]
