# Generated by Django 4.0.6 on 2022-09-25 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('87a59ebd-87e3-4b6c-99c1-88ea9d2e0d45')),
        ),
    ]
