# Generated by Django 4.0.6 on 2022-09-25 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0075_alter_inventory_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('d3c0cc9a-bf76-4653-afb5-894a878a1d5d')),
        ),
    ]
