# Generated by Django 4.0.6 on 2022-10-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_supplier_address_alter_supplier_city_and_more'),
        ('inventory', '0078_alter_inventory_pack_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='facility',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility', to='accounts.facility'),
        ),
    ]
