# Generated by Django 4.0.6 on 2022-11-12 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0080_alter_site_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.CharField(choices=[('Warehouse', 'Warehouse'), ('Pre-Delivered', 'Pre-Delivered'), ('In-Transit', 'In-Transit')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.site'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='logistic_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_areas', to='inventory.logisticarea'),
        ),
    ]
