# Generated by Django 4.0.6 on 2022-11-12 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0081_inventorymanager_inventory_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='site',
        ),
    ]
