# Generated by Django 4.0.6 on 2022-11-19 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('formulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('Ordered', 'Ordered'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Ordered', max_length=50, verbose_name='Order Status')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('payment_terms', models.CharField(choices=[('90 days due net', '90 days due net'), ('60 days due net', '60 days due net'), ('30 days due net', '60 days due net'), ('15 days due net', '15 days due net'), ('Pay In Advance', 'Pay In Advance'), ('Cash On Delivery', 'Cash On Delivery'), ('Cash In Advance', 'Cash In Advance')], max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(null=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.facility')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_quantity', models.IntegerField()),
                ('delivered_quantity', models.IntegerField(default=0)),
                ('planned_quantity', models.IntegerField(blank=True)),
                ('unit_price', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0, max_length=5, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.productlist')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_products', to='inbound.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Unload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Process', 'In Process'), ('Finished', 'Finished')], default='Not Started', max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('logistic_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.logisticarea')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inbound.purchaseorder')),
                ('site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.site')),
            ],
        ),
        migrations.CreateModel(
            name='UnloadProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_quantity', models.IntegerField(default=0)),
                ('planned_quantity', models.IntegerField(default=0)),
                ('actual_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.productlist')),
                ('unload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unload_products', to='inbound.unload')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbound.purchaseorderproduct')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbound.purchaseorder')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='products',
            field=models.ManyToManyField(related_name='purchaseorders', through='inbound.PurchaseOrderProduct', to='formulary.productlist'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier'),
        ),
        migrations.CreateModel(
            name='IdentifiedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=225, null=True)),
                ('expiration_date', models.DateField()),
                ('stock_identifier', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Unique Identifier')),
                ('split_quantity', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('target_logistic_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.logisticarea')),
                ('unload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identified_stock', to='inbound.unload')),
                ('unload_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identified_stock', to='inbound.unloadproduct')),
            ],
        ),
    ]
