# Generated by Django 4.0.6 on 2022-08-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventory_site_id_inventory_batch_and_more'),
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='inbound_status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Put_Away',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('put_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.site')),
            ],
        ),
    ]
