# Generated by Django 4.0.6 on 2022-11-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='unit_of_measure',
            field=models.CharField(blank=True, choices=[('Volume in Mls', 'Volume in Mls'), ('Weight in Grams', 'Weight in Grams'), ('Packs', 'Packs'), ('Units', 'Units')], default='Packs', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='unloadproduct',
            name='unit_of_measure',
            field=models.CharField(blank=True, choices=[('Volume in Mls', 'Volume in Mls'), ('Weight in Grams', 'Weight in Grams'), ('Packs', 'Packs'), ('Units', 'Units')], default='Packs', max_length=30, null=True),
        ),
    ]
