# Generated by Django 4.0.6 on 2022-08-27 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_supplier_supplied_products'),
        ('inventory', '0006_remove_inventory_site_id_inventory_batch_and_more'),
        ('inbound', '0002_alter_purchaseorder_inbound_status_put_away'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='inbound_site',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.facility'),
        ),
        migrations.AddField(
            model_name='put_away',
            name='put_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.logisticarea'),
        ),
        migrations.AddField(
            model_name='put_away',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('In Process', 'In Process'), ('Finished', 'Finished')], max_length=225, null=True),
        ),
        migrations.CreateModel(
            name='Unload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Process', 'In Process'), ('Finished', 'Finished')], max_length=100)),
                ('unload_qty', models.IntegerField()),
                ('purchase_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbound.purchaseorderproduct')),
                ('site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.site')),
                ('unload_area', models.ForeignKey(default='REC_BAY', on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.logisticarea')),
            ],
        ),
        migrations.AddField(
            model_name='put_away',
            name='final_unload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inbound.unload'),
        ),
    ]
