# Generated by Django 4.0.6 on 2022-08-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0004_purchaseorderproduct_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderproduct',
            old_name='batch_nummber',
            new_name='batch_number',
        ),
    ]
