# Generated by Django 4.0.6 on 2022-08-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0005_rename_batch_nummber_purchaseorderproduct_batch_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unload',
            name='purchase_product',
        ),
        migrations.AddField(
            model_name='unload',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inbound.purchaseorder'),
        ),
    ]
