# Generated by Django 4.0.6 on 2022-08-27 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0006_remove_unload_purchase_product_unload_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('39c5bb88-6833-44e3-a208-96d4670c0065'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
