# Generated by Django 4.0.6 on 2022-08-27 16:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventory_stock_identifier'),
        ('inbound', '0009_remove_purchaseorder_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='put_away',
            name='put_area',
        ),
        migrations.RemoveField(
            model_name='unload',
            name='unload_qty',
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inbound.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('a94647ad-d356-4855-b2c2-25ca885d1880'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
        migrations.CreateModel(
            name='UnloadProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unload_qty', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('purchase_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inbound.purchaseorderproduct')),
                ('unload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inbound.unload')),
            ],
        ),
        migrations.CreateModel(
            name='PutAwayProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('put_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.logisticarea')),
                ('putaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putaway_products', to='inbound.put_away')),
                ('unload_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inbound.unloadproduct')),
            ],
        ),
    ]
