# Generated by Django 4.0.6 on 2022-08-27 23:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0010_remove_put_away_put_area_remove_unload_unload_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='inbound_status',
            new_name='order_status',
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('20cb981e-5750-449f-abd9-d99fde4d7af5'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
        migrations.AlterField(
            model_name='putawayproduct',
            name='unload_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inbound.unloadproduct'),
        ),
        migrations.AlterField(
            model_name='unloadproduct',
            name='purchase_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inbound.purchaseorderproduct'),
        ),
    ]
