# Generated by Django 4.0.6 on 2022-08-28 00:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0010_remove_manufacturer_brand_name_and_more'),
        ('inbound', '0011_rename_inbound_status_purchaseorder_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='discount',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='products',
            field=models.ManyToManyField(related_name='purchaseorders', through='inbound.PurchaseOrderProduct', to='formulary.product_list'),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.product_list'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbound.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('c77ffc5d-020e-4546-bdf2-5e0d9154ef27'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
