# Generated by Django 4.0.6 on 2022-08-28 00:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0010_remove_manufacturer_brand_name_and_more'),
        ('inbound', '0012_remove_purchaseorder_discount_purchaseorder_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.product_list'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inbound.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('61555c0d-ea89-4e0e-887b-0ceedae04cb4'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
