# Generated by Django 4.0.6 on 2022-08-28 00:42

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0013_alter_purchaseorderproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unload',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('cd9e0319-15fc-4e78-8819-392d3954a2ac'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
