# Generated by Django 4.0.6 on 2022-08-28 00:52

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0014_unload_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='put_away',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('60a62be2-f74b-406d-85ef-8d2ce4982bf9'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
