# Generated by Django 4.0.6 on 2022-08-28 00:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0015_put_away_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Ordered', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('9fef56be-a1db-49ec-803c-94f31a924f6a'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
        migrations.AlterField(
            model_name='put_away',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('In Process', 'In Process'), ('Finished', 'Finished')], default='Not Started', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='unload',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Process', 'In Process'), ('Finished', 'Finished')], default='Not Started', max_length=15),
        ),
    ]
