# Generated by Django 4.0.6 on 2022-08-28 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_inventory_stock_identifier'),
        ('inbound', '0016_alter_purchaseorder_order_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Put_Away',
            new_name='PutAway',
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('bb1a65ec-232c-4743-9172-4328131a963b'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
