# Generated by Django 4.0.6 on 2022-09-01 22:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_supplier_supplied_products'),
        ('inbound', '0018_alter_purchaseorderproduct_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('89e8a901-1540-4475-9214-9c07fda24176'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
