# Generated by Django 4.0.6 on 2022-09-01 23:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0019_alter_purchaseorder_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('b1267c51-f3f7-4710-a1a2-fe0affa26e52'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
