# Generated by Django 4.0.6 on 2022-09-01 23:30

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0020_purchaseorder_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 1, 23, 30, 24, 51131)),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('7b0cd933-0827-4b0f-b6e3-09afb1d0844f'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
