# Generated by Django 4.0.6 on 2022-09-01 23:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0021_purchaseorder_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 1, 23, 31, 12, 561444, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('e29b1d6d-2d7e-4886-a645-79ac76ea029f'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
