# Generated by Django 4.0.6 on 2022-09-01 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0022_alter_purchaseorder_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(default='django.utils.timezone.now'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('c9f4a8e5-1250-428a-9e70-e6b3a1eab43b'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
