# Generated by Django 4.0.6 on 2022-09-02 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0023_alter_purchaseorder_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('c7ff5746-9bba-4cf0-91ab-9e7814c5e683'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
