# Generated by Django 4.0.6 on 2022-09-03 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0024_alter_purchaseorderproduct_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('67d98f90-ee98-48b9-9f4f-5db922441acb'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
