# Generated by Django 4.0.6 on 2022-09-03 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0025_alter_purchaseorderproduct_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='discount',
            field=models.FloatField(default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('665d7e94-5641-43c3-9594-e574e9ba5293'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
