# Generated by Django 4.0.6 on 2022-09-03 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0026_alter_purchaseorderproduct_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('5f79dd80-dfad-4ebc-b0f1-29324a757449'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
