# Generated by Django 4.0.6 on 2022-09-03 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0028_alter_purchaseorder_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(default='django.utils.timezone.now'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('9f05bb2d-b019-4002-9b48-68e122c5ba96'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
