# Generated by Django 4.0.6 on 2022-09-03 15:28

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0029_alter_purchaseorder_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('b4090318-5c87-4caa-a516-cc3b84c47489'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
