# Generated by Django 4.0.6 on 2022-09-03 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0030_alter_purchaseorder_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('87580f3c-78b7-458d-ac1f-4d1dce34f170'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
