# Generated by Django 4.0.6 on 2022-09-03 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0031_alter_purchaseorderproduct_stock_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('91cdfb77-c642-446d-8cfd-a9ea28427830'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
