# Generated by Django 4.0.6 on 2022-09-04 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0035_alter_purchaseorderproduct_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('19bc26ba-524f-4bab-9cad-28043598c7a8'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
