# Generated by Django 4.0.6 on 2022-09-04 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0036_alter_purchaseorderproduct_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('2b7e3f9b-c366-4151-b9de-2b56124aafd1'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
