# Generated by Django 4.0.6 on 2022-09-04 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0037_alter_purchaseorderproduct_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('55641e3c-fc2f-4646-bf5e-35d9d035ab88'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
