# Generated by Django 4.0.6 on 2022-09-04 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0038_alter_purchaseorderproduct_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('a39ef460-98ac-40aa-8a16-10f3e1c1c404'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
