# Generated by Django 4.0.6 on 2022-09-05 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0039_alter_purchaseorderproduct_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('636c8ed5-7a85-466b-8ddf-816c5895b933'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
