# Generated by Django 4.0.6 on 2022-09-18 00:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0040_alter_purchaseorderproduct_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('08a0d3fd-18f6-4fb2-a159-e8a0225ca058'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
