# Generated by Django 4.0.6 on 2022-09-18 00:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0041_alter_purchaseorderproduct_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('390f819a-d519-4900-8a6d-77fa8a8ff51a'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
