# Generated by Django 4.0.6 on 2022-09-18 01:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0042_alter_purchaseorderproduct_stock_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderproduct',
            old_name='cost_price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(choices=[('90 days due net', '90 days due net'), ('60 days due net', '60 days due net'), ('30 days due net', '60 days due net'), ('15 days due net', '15 days due net'), ('Pay In Advance', 'Pay In Advance'), ('Cash On Delivery', 'Cash On Delivery'), ('Cash In Advance', 'Cash In Advance')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Ordered', max_length=50, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('6204822c-48a8-460b-9172-267f16cae298'), editable=False, null=True, verbose_name='unique_identifier'),
        ),
    ]
