# Generated by Django 4.0.6 on 2022-09-18 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_alter_inventory_stock_identifier'),
        ('inbound', '0044_rename_supplied_qty_purchaseorderproduct_open_quantiy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='putaway',
            old_name='put_site',
            new_name='site_id',
        ),
        migrations.RenameField(
            model_name='putawayproduct',
            old_name='put_area',
            new_name='target_logistic_area',
        ),
        migrations.RenameField(
            model_name='unload',
            old_name='unload_area',
            new_name='target_logistic_area',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='stock_identifier',
        ),
        migrations.RemoveField(
            model_name='putawayproduct',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='putawayproduct',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='unloadproduct',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='unloadproduct',
            name='unload_qty',
        ),
        migrations.RemoveField(
            model_name='unloadproduct',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='putaway',
            name='source_logistic_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.logisticarea'),
        ),
        migrations.AddField(
            model_name='putaway',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='putawayproduct',
            name='actual_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='putawayproduct',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='putawayproduct',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='putawayproduct',
            name='open_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='putawayproduct',
            name='stock_identifier',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unload',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unloadproduct',
            name='actual_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unloadproduct',
            name='open_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unloadproduct',
            name='unload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unload_products', to='inbound.unload'),
        ),
        migrations.CreateModel(
            name='IdentifiedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=225, null=True)),
                ('expiration_date', models.DateField()),
                ('stock_identifier', models.UUIDField(blank=True, default=uuid.UUID('b933e677-1f38-42b4-a276-ca041e30a93b'), editable=False, null=True, verbose_name='Unique Identifier')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('unload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_stock', to='inbound.unloadproduct')),
            ],
        ),
    ]
