# Generated by Django 4.0.6 on 2022-09-18 11:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_alter_inventory_stock_identifier'),
        ('inbound', '0046_alter_identifiedstock_stock_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='site_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.site'),
        ),
        migrations.AlterField(
            model_name='identifiedstock',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('8eda0d34-889a-4751-81b2-7bc28f57692e'), editable=False, null=True, verbose_name='Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_products', to='inbound.purchaseorder'),
        ),
    ]
