# Generated by Django 4.0.6 on 2022-09-18 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0047_purchaseorder_site_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiedstock',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('10796bcb-3ff9-47f5-9bab-3a8ac7ba3e7c'), editable=False, null=True, verbose_name='Unique Identifier'),
        ),
    ]
