# Generated by Django 4.0.6 on 2022-09-18 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0048_alter_identifiedstock_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiedstock',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('95681604-16e6-4eb0-9d25-3420a673f095'), editable=False, null=True, verbose_name='Unique Identifier'),
        ),
    ]
