# Generated by Django 4.0.6 on 2022-09-18 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0049_alter_identifiedstock_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiedstock',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('a123fa62-53dc-40bb-a777-41a2fc71bc5a'), editable=False, null=True, verbose_name='Unique Identifier'),
        ),
    ]
