# Generated by Django 4.0.6 on 2022-09-18 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0050_alter_identifiedstock_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiedstock',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('b3210093-5238-4dc5-b399-c2f8d9420358'), editable=False, null=True, verbose_name='Unique Identifier'),
        ),
    ]
