# Generated by Django 4.0.6 on 2022-09-18 21:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_alter_inventory_stock_identifier_and_more'),
        ('inbound', '0051_alter_identifiedstock_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiedstock',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('e7b20a3b-77e2-41fd-8ea6-bae4f2399040'), editable=False, null=True, verbose_name='Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='unload',
            name='target_logistic_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.logisticarea'),
        ),
    ]
