# Generated by Django 4.0.6 on 2022-09-18 23:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0052_alter_identifiedstock_stock_identifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identifiedstock',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='identifiedstock',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('6fa700f7-ee6a-426e-835e-f154de6cee89'), editable=False, null=True, verbose_name='Unique Identifier'),
        ),
    ]
