# Generated by Django 4.0.6 on 2022-09-19 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0054_rename_open_quantiy_purchaseorderproduct_open_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='planned_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identifiedstock',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('e5a7c672-4ead-47f6-8eea-312537d51ae4'), editable=False, null=True, verbose_name='Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='putawayproduct',
            name='actual_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
