# Generated by Django 4.0.6 on 2022-09-19 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0058_identifiedstock_split_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseOrderTransactions',
            new_name='PurchaseOrderTransaction',
        ),
        migrations.AlterField(
            model_name='identifiedstock',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('58bc1111-ae0f-45a1-92b8-3071884aab52'), editable=False, null=True, verbose_name='Unique Identifier'),
        ),
    ]
