# Generated by Django 4.0.6 on 2022-09-19 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0060_purchaseorderproductmanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiedstock',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('84a3eaa0-b048-444f-bf28-7329dd4931b0'), editable=False, null=True, verbose_name='Unique Identifier'),
        ),
    ]
