# Generated by Django 4.0.6 on 2022-09-20 03:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0061_alter_identifiedstock_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiedstock',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('06085e4b-bc58-4b14-9684-e9601273bb0d'), editable=False, null=True, verbose_name='Unique Identifier'),
        ),
    ]
