# Generated by Django 4.0.6 on 2022-09-23 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0063_alter_identifiedstock_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiedstock',
            name='stock_identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('ae74fa05-c58d-492a-9e74-fb5fb3974861'), editable=False, null=True, verbose_name='Unique Identifier'),
        ),
    ]
