# Generated by Django 4.0.6 on 2022-09-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0065_alter_identifiedstock_stock_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purchase_order_id',
        ),
    ]
