# Generated by Django 4.0.6 on 2022-09-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0066_remove_purchaseorder_purchase_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='unit_price',
            field=models.FloatField(default=0.0),
        ),
    ]
