# Generated by Django 4.0.6 on 2022-10-02 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0067_alter_purchaseorderproduct_unit_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseOrderProductManager',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='site_id',
        ),
    ]
