# Generated by Django 4.0.6 on 2022-10-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0068_delete_purchaseorderproductmanager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='actual_delivery_date',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
