# Generated by Django 4.0.6 on 2022-10-10 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0069_remove_purchaseorder_actual_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identifiedstock',
            old_name='unload',
            new_name='unload_product',
        ),
    ]
