# Generated by Django 4.0.6 on 2022-10-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0015_alter_manufacturer_tier'),
        ('inbound', '0070_rename_unload_identifiedstock_unload_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='putaway',
            old_name='final_unload',
            new_name='unload',
        ),
        migrations.RemoveField(
            model_name='putawayproduct',
            name='unload_product',
        ),
        migrations.RemoveField(
            model_name='unloadproduct',
            name='purchase_product',
        ),
        migrations.AddField(
            model_name='putawayproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.productlist'),
        ),
        migrations.AddField(
            model_name='unloadproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.productlist'),
        ),
    ]
