# Generated by Django 4.0.6 on 2022-10-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0071_rename_final_unload_putaway_unload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unloadproduct',
            name='planned_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
