# Generated by Django 4.0.6 on 2022-11-12 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0072_unloadproduct_planned_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='putawayproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='putawayproduct',
            name='putaway',
        ),
        migrations.RemoveField(
            model_name='putawayproduct',
            name='target_logistic_area',
        ),
        migrations.DeleteModel(
            name='PutAway',
        ),
        migrations.DeleteModel(
            name='PutAwayProduct',
        ),
    ]
