# Generated by Django 4.0.6 on 2022-11-13 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0082_remove_inventory_site'),
        ('inbound', '0073_remove_putawayproduct_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unload',
            name='target_logistic_area',
        ),
        migrations.AddField(
            model_name='identifiedstock',
            name='target_logistic_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.logisticarea'),
        ),
    ]
