# Generated by Django 4.0.6 on 2022-11-13 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0074_remove_unload_target_logistic_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifiedstock',
            name='unload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identified_stock', to='inbound.unload'),
        ),
        migrations.AlterField(
            model_name='identifiedstock',
            name='unload_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identified_stock', to='inbound.unloadproduct'),
        ),
    ]
