# Generated by Django 4.0.6 on 2022-11-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='unit_of_measure',
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milliliters', models.PositiveIntegerField(verbose_name='mls')),
                ('gram', models.PositiveIntegerField(verbose_name='g')),
                ('pack', models.PositiveIntegerField(verbose_name='pack')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_of_measure', to='formulary.productlist')),
            ],
        ),
    ]
