# Generated by Django 4.0.6 on 2022-11-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0002_remove_productlist_unit_of_measure_unitofmeasure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitofmeasure',
            old_name='milliliters',
            new_name='milliliter',
        ),
    ]
