# Generated by Django 4.0.6 on 2022-08-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0002_rename_brand_name_form_form_brand_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='form',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generic_attr',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
