# Generated by Django 4.0.6 on 2022-08-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0003_brand_is_active_category_is_active_form_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_list',
            name='product_brand',
        ),
        migrations.RemoveField(
            model_name='product_list',
            name='product_tier',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='brand_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='price_range',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='tier',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Tier',
        ),
    ]
