# Generated by Django 4.0.6 on 2022-11-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0003_rename_milliliters_unitofmeasure_milliliter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='gram',
            field=models.PositiveIntegerField(verbose_name='Weight in Gram'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='milliliter',
            field=models.PositiveIntegerField(verbose_name='Volume in Mls'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='pack',
            field=models.PositiveIntegerField(verbose_name='Pack'),
        ),
    ]
