# Generated by Django 4.0.6 on 2022-08-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0004_remove_product_list_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='details',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
    ]
