# Generated by Django 4.0.6 on 2022-11-21 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0004_alter_unitofmeasure_gram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_uom', to='formulary.productlist'),
        ),
    ]
