# Generated by Django 4.0.6 on 2022-08-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0005_product_list_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_list',
            old_name='product_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product_list',
            old_name='product_generic_name',
            new_name='generic_name',
        ),
        migrations.RenameField(
            model_name='product_list',
            old_name='product_manufacturer',
            new_name='manufacturer',
        ),
    ]
