# Generated by Django 4.0.6 on 2022-11-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0005_alter_unitofmeasure_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='gram',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight in Gram'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='milliliter',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume in Mls'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='pack',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pack'),
        ),
    ]
