# Generated by Django 4.0.6 on 2022-08-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0006_rename_product_category_product_list_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
