# Generated by Django 4.0.6 on 2022-08-26 15:04

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0007_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='product_id',
            field=models.CharField(max_length=225, verbose_name=django.db.models.aggregates.Aggregate('pkproduct_name')),
        ),
    ]
