# Generated by Django 4.0.6 on 2022-11-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0007_unitofmeasure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_uom', to='formulary.productlist'),
        ),
    ]
