# Generated by Django 4.0.6 on 2022-08-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0008_alter_product_list_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_list',
            name='product_id',
        ),
    ]
