# Generated by Django 4.0.6 on 2022-11-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0008_alter_unitofmeasure_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='pack',
            field=models.IntegerField(blank=True, null=True, verbose_name='Units Per Pack'),
        ),
    ]
