# Generated by Django 4.0.6 on 2022-08-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0009_remove_product_list_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='product_list',
            name='generic_name',
        ),
        migrations.DeleteModel(
            name='Generic_Attr',
        ),
    ]
