# Generated by Django 4.0.6 on 2022-08-28 01:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0021_alter_inventory_stock_identifier'),
        ('inbound', '0018_alter_purchaseorderproduct_stock_identifier'),
        ('formulary', '0010_remove_manufacturer_brand_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_List',
            new_name='ProductList',
        ),
    ]
