# Generated by Django 4.0.6 on 2022-09-18 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0012_alter_productlist_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='formulary.category'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='product_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_products', to='formulary.form'),
        ),
    ]
