# Generated by Django 4.0.6 on 2022-09-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0013_alter_productlist_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
